# Generated by Django 6.0.2 on 2026-02-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_person_vaqt_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.IntegerField(default=10)),
                ('max_score', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.testmodule'),
        ),
    ]
