# Generated by Django 6.0.2 on 2026-02-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_testmodule_alter_testresult_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shior',
            field=models.CharField(default='Biz yurishda davom etamiz!', max_length=250),
        ),
    ]
