# Generated by Django 6.0.2 on 2026-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_person_shior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='shior',
            field=models.CharField(max_length=250),
        ),
    ]
