# Generated by Django 6.0.2 on 2026-02-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0007_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_correct',
        ),
    ]
