# Generated by Django 6.0.2 on 2026-02-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0008_remove_question_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='shior',
        ),
    ]
